server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      force-response: true
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://220.123.184.56:3306/carbble?characterEncoding=UTF-8&serverTimezone=Asia/seoul
    username: carbble
    password: 1234

logging:
  file:
    path: ./logs
    max-history: 30
    max-size: 10MB
    level:
      root: info
      #org.apache.http: debug
      org.apache.http: info
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
